import { toPng } from 'html-to-image';
import jsPDF from 'jspdf';
import { Node, Edge } from '@xyflow/react';

// Export Canvas to PDF
export async function exportCanvasToPDF(elementId: string) {
  const canvasElement = document.getElementById(elementId);
  if (!canvasElement) return;

  try {
    const dataUrl = await toPng(canvasElement, {
      backgroundColor: '#0a0a0a', // Assuming dark mode based on QueryMind vibe
      style: {
        transform: 'scale(1)', // Fix scale rendering issues if canvas is zoomed
      }
    });

    const pdf = new jsPDF({
      orientation: 'landscape',
      unit: 'px',
      format: [canvasElement.offsetWidth, canvasElement.offsetHeight],
    });

    pdf.addImage(dataUrl, 'PNG', 0, 0, canvasElement.offsetWidth, canvasElement.offsetHeight);
    pdf.save('db-schema-design.pdf');
  } catch (error) {
    console.error('Failed to export PDF', error);
  }
}

// Map Design to PostgreSQL
export function exportToSQL(tables: any[], edges: Edge[]): string {
  let sql = '-- Generated by QueryMind DB Design AI\n\n';

  tables.forEach(table => {
    sql += `CREATE TABLE "${table.name}" (\n`;
    
    table.columns.forEach((col: any, index: number) => {
      let line = `  "${col.name}" ${col.type}`;
      if (col.isPrimary) line += ' PRIMARY KEY';
      if (col.constraints) line += ` ${col.constraints}`;
      
      if (index < table.columns.length - 1) line += ',';
      sql += line + '\n';
    });
    
    sql += `);\n\n`;
  });

  if (edges.length > 0) {
    sql += '-- Foreign Keys\n';
    edges.forEach(edge => {
      const sourceTable = tables.find(t => t.id === edge.source);
      const targetTable = tables.find(t => t.id === edge.target);
      
      if (sourceTable && targetTable) {
        const sourceColName = `${targetTable.name.toLowerCase()}_id`;
        
        // Ensure the foreign key column exists in the source table data
        const hasCol = sourceTable.columns.find((c: any) => c.name === sourceColName);
        if (!hasCol) {
          sql += `ALTER TABLE "${sourceTable.name}" ADD COLUMN "${sourceColName}" UUID;\n`;
        }
        
        sql += `ALTER TABLE "${sourceTable.name}" ADD CONSTRAINT "fk_${sourceTable.name.toLowerCase()}_${targetTable.name.toLowerCase()}"\n`;
        sql += `  FOREIGN KEY ("${sourceColName}") REFERENCES "${targetTable.name}" ("id");\n\n`;
      }
    });
  }

  return sql;
}
